### ISSUE TITLE
no id in self.reply

### ISSUE THREAD

**Issue by 51963002** [menekevin/xmr-miner#1] opened 2018-06-18 07:32 UTC
connect to f2pool

**Comment by menekevin** [comment] 2018-06-19 05:41
pls can you give me more details? thanks.

**Comment by 51963002** [comment] 2018-06-20 21:54
In client.py ：
if rid_1 in self.reply or rid_2 in self.reply or rid_3 in self.reply or rid_4 in self.reply:
                        break
There is no rid in the information returned by the mineral pool

**Comment by menekevin** [comment] 2018-06-24 18:31
rid is a sort of literal expression used by client to sync requests with responses. Have you tried passing the --debug parameter to the miner? With it you can check the communication chain between miner and server. I had no time to check your pool until now, tomorrow I will do a try and will say you about the error. With other pools such ad xmrpool.net there is no problem I think.

**Comment by menekevin** [comment] 2018-06-25 12:03
Ok. I've tried with f2pool. The problem is that the server's pool returns double job message after the login. Retrying the login (default action) got no server's response. Sorry but, until now, this happened to me only with this pool. Please wait, I will workaround this as soon as possible, so you can start to mine from f2pool with xmr-miner.

This is the debug chain:

    xmr-miner -o xmr.f2pool.com:13531 -u 425WpsFRHUrBxqMN9JkE4KJhso4u5jLAHEZ6B5ZGacpGDpXfmeTwoVgjmKw2WxRswB2kFFdBJC872GJqoD44gyMLSiMLDH -p x -d
    *** xmr-miner ***

    [Thread #1] Connecting to xmr.f2pool.com:13531...

    [Thread #1] Sending message #1:
    {"jsonrpc": "2.0", "id": 1, "method": "login", "params": {"login": "425WpsFRHUrBxqMN9JkE4KJhso4u5jLAHEZ6B5ZGacpGDpXfmeTwoVgjmKw2WxRswB2kFFdBJC872GJqboD44gyMLSiMLDH", "pass": "x", "agent": "xmr-miner"}}

    [Thread #1] Receiving message #1:
    {"id": 1, "error": null, "result": {"id": "4446", "status": "OK", "job": {"blob": "0707b1acc3d9057b072fc17fe09ad4b886866bd35d53068cdcb698e4fa71ccf1a02705cf70654400000000f24d15b4818adf294ec737c1668f538a3ccc98e1bc1591d24d8c8c51d793440f06", "job_id": "IYoMKRSDyA", "target": "ffff0300"}}}
    {"method": "job", "params": {"blob": "0707b1acc3d9057b072fc17fe09ad4b886866bd35d53068cdcb698e4fa71ccf1a02705cf70654400000000f4d15b4818adf294ec737c1668f538a3ccc98e1bc1591d24d8c8c51d793440f06", "job_id": "IYoMKRSDyA", "target": "ffff0300"}}

     [Thread #1] Invalid credentials or malformed job message! Retrying...

     [Thread #1] Sending message #2:
     {"jsonrpc": "2.0", "id": 2, "method": "login", "params": {"login": "425WpsFRHUrBxqMN9JkE4KJhso4u5jLAHEZ6B5ZGacpGDpXfmeTwoVgjmKw2WxRswB2kFFdBJC872GJqboD44gyMLSiMLDH", "pass": "x", "agent": "xmr-miner"}}

    <NO RESPONSE>

In fact, the first server's response is a double one, but the assigned job is valid anyway. Furthermore, the server got no response, because it's waiting for a valid message from our client I think.

Unfortunately, every server's pool do the things in own way (despite the miner's pool RPC JSON 2.0 specifications) and we've to adapt our clients in order to be compatible with all ones.

I hope to be able to upload a new release in a few days or maximum in a week.

Thanks for your reporting!

**Comment by menekevin** [comment] 2018-06-25 13:54
xmr-miner 1.0.1 released now! Soon I will upload the deb updated package also. I'll close the issue. If you have any problem, feel free to contact me directly or open a new issue.

K.

**Closed by menekevin** 2018-06-25 13:54 UTC
